### ISSUE TITLE
whats the problem?.....

### ISSUE THREAD

**Issue by 687766616e** [Hax4us/Metasploit_termux#15]
`$ chmod +x metasploit.sh && ./metasploit.sh`
```
find: ‘/data/data/com.termux/files/home/sql/mytxt’: Permission denied
find: ‘/data/data/com.termux/files/home/.suroot’: Permission denied
find: ‘/data/data/com.termux/files/home/metasploit-framework’: No such file or directory
Get:1 https://termux.net stable InRelease [1720 B]
Ign:2 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Hit:3 https://grimler.se root InRelease
```

**Comment by huitc** [comment]
```
Setting up tar (1.32) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136    0   136    0     0    150      0 --:--:-- --:--:-- --:--:--   150
100 27.6M  100 27.6M    0     0  1389k      0  0:00:20  0:00:20 --:--:-- 2779k
Traceback (most recent call last):
        19: from /data/data/com.termux/files/usr/bin/gem:9:in `<main>'
        18: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/gem_runner.rb:86:in `<top (required)>'
        15: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems.rb:1111:in `load_plugins'
        14: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems.rb:546:in `find_latest_files'
        13: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1131:in `latest_specs'
        12: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:747:in `_all'
        11: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:826:in `stubs'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:788:in `installed_stubs'
         9: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `map_stubs'
         8: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `flat_map'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `each'
         6: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:798:in `block in map_stubs'
         5: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:774:in `gemspec_stubs_in'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:774:in `select'
         3: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:204:in `valid?'
         2: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `data'
         1: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `open'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `initialize': Permission denied @ rb_sysopen - /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/specifications/bundler-2.0.1.gemspec (Errno::EACCES)
Traceback (most recent call last):
        15: from /data/data/com.termux/files/usr/bin/bundle:23:in `<main>'
        14: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
        13: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems.rb:272:in `find_spec_for_exe'
        12: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:280:in `matching_specs'
        11: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:847:in `stubs_for'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:788:in `installed_stubs'
         9: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `map_stubs'
         8: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `flat_map'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:795:in `each'
         6: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:798:in `block in map_stubs'
         5: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:774:in `gemspec_stubs_in'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:774:in `select'
         3: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:204:in `valid?'
         2: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `data'
         1: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `open'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb:114:in `initialize': Permission denied @ rb_sysopen - /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/specifications/bundler-2.0.1.gemspec (Errno::EACCES)
Gems installed
```

**Comment by huitc** [comment]
```
Creating database
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    486      0 --:--:-- --:--:-- --:--:--   486
The files belonging to this database system will be owned by user "u0_a1011".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: directory "/data/data/com.termux/files/usr/var/lib/postgresql" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/data/data/com.termux/files/usr/var/lib/postgresql" or run initdb
with an argument other than "/data/data/com.termux/files/usr/var/lib/postgresql".
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2019-03-03 18:19:26.102 HKT [14549] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-03-03 18:19:26.109 HKT [14549] LOG:  listening on Unix socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"
2019-03-03 18:19:26.156 HKT [14553] LOG:  database system was interrupted; last known up at 2019-03-01 10:16:47 HKT
.2019-03-03 18:19:27.036 HKT [14553] LOG:  database system was not properly shut down; automatic recovery in progress
2019-03-03 18:19:27.043 HKT [14553] LOG:  redo starts at 0/15E1518
2019-03-03 18:19:27.043 HKT [14553] LOG:  invalid record length at 0/15E1550: wanted 24, got 0
2019-03-03 18:19:27.043 HKT [14553] LOG:  redo done at 0/15E1518
2019-03-03 18:19:27.084 HKT [14549] LOG:  database system is ready to accept connections
 done
server started
2019-03-03 18:19:27.226 HKT [14566] ERROR:  role "msf" already exists
2019-03-03 18:19:27.226 HKT [14566] STATEMENT:  CREATE ROLE msf NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
createuser: creation of new role failed: ERROR:  role "msf" already exists
2019-03-03 18:19:27.273 HKT [14569] ERROR:  database "msf_database" already exists
2019-03-03 18:19:27.273 HKT [14569] STATEMENT:  CREATE DATABASE msf_database;
createdb: database creation failed: ERROR:  database "msf_database" already exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   808  100   808    0     0   1088      0 --:--:-- --:--:-- --:--:--  1087
you can directly use msfvenom or msfconsole rather than ./msfvenom or ./msfconsole.
$ ./msfconsole
bash: ./msfconsole: No such file or directory
```

**Comment by nikhilsuvarna89** [comment]
Try navigating inside the msf directory and then run ./msfconsole

**Comment by ruthwik316** [comment]
Not working nikhil

**Comment by nikhilsuvarna89** [comment]
Post the error log

**Comment by nikhilsuvarna89** [comment]
> Not working nikhil
> New error is coming
post the error log

**Comment by Hax4us** [comment]
Please reinstall the metasploit from my updated script
