### ISSUE TITLE
metasploit-credential not in the bundle

### ISSUE THREAD

**Issue by gilgamesh-su** [Hax4us/Metasploit_termux#35]
I have this error on termux, please help me

$ msfconsole                                            metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        13: from /data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole:15:in `<main>'
        12: from /data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole:15:in `require'
        11: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
         9: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
         7: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
         6: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core.rb:44:in `require'
         5: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>'
         3: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
         2: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
         1: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:22:in `require': cannot load such file -- metasploit/credential (LoadError)
        13: from /data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole:15:in `<main>'
        12: from /data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole:15:in `require'
        11: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
         9: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
         7: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
         6: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core.rb:44:in `require'
         5: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>'
         3: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
         2: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
         1: from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0x00000071875edb90> (NoMethodError)

**Comment by gilgamesh-su** [comment]
Solved uninstalling termux and reinstalling
